### ISSUE TITLE
Implement show/import previous work for Dialog Guidance components

### ISSUE THREAD

**Issue by breity** [WISE-Community/WISE-Client#382] opened 2021-10-26 16:21 UTC
### Description

Allow authors to show and import previous work (via Connected Components) for Dialog Guidance components. Show work should display previous Dialog Guidance conversation as read-only. Import work should import previous responses and allow student to continue conversation.

**Comment by hirokiterashima** [comment] 2021-11-09 18:09
duplicate of #376

**Closed as completed by hirokiterashima** 2021-11-09 18:09 UTC
Labels: feature request
